spring:
  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:testDB?enabledTLSProtocols=TLSv1.2&serverTimezone=Asia/Seoul&sendFractionalSeconds=false;DB_CLOSE_DELAY=-1;MODE=MYSQL
    username: sa
    password:
    hikari:
      data-source-properties:
        rewriteBatchedStatements: true
      maximum-pool-size: 3

  jpa:
#    database: mysql
#    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect

    open-in-view: false

    hibernate:
      ddl-auto: create-drop

    properties:
      hibernate:
        jdbc:
          batch_size: 1000

        format_sql: true
#        default_batch_fetch_size: 1000
        show_sql: true

    defer-datasource-initialization: true

  data:
    web:
      pageable:
        max-page-size: 50
        default-page-size: 10

springfox:
  documentation:
    openApi:
      v3:
        path: /portals/v3/api-docs
